import subprocess
import io

from datetime import datetime


def execute_start_script():
    subprocess.call(["/var/lib/tsuru/start"])


def save_apprc_file(environs):
    with io.open("/home/application/apprc") as file:
        file.write(u"# generated by tsuru at {}\n".format(datetime.now()))
        for key, value in environs.items():
            file.write(u'export {}="{}"\n'.format(key, value))
