import subprocess
import io

from datetime import datetime


def execute_start_script():
    subprocess.call(["/var/lib/tsuru/start"])


def save_apprc_file(environs):
    with io.open("/home/application/apprc") as file:
        file.write(u"# generated by tsuru at {}\n".format(datetime.now()))
        for env in environs:
            file.write(u'export {}="{}"\n'.format(env["name"], env["value"]))
